version: "3.7"
services:
  app:
    build:
      args:
        user: lumen
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pubsub
    container_name: pubsub-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pubsub

  db:
    image: mysql:5.7
    container_name: pubsub-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - pubsub

  nginx:
    image: nginx:latest
    container_name: pubsub-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - pubsub

  redis:
    container_name: pubsub-redis
    image: redis:4
    ports:
      - 6379:6379
    volumes:
      - "./redis:/usr/local/etc/redis"
    command: ["redis-server"]
    networks:
      - pubsub

networks:
  pubsub:
    driver: bridge
